# Generated by Django 3.1.7 on 2021-07-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210627_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='course',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='student_class',
        ),
    ]
