# Generated by Django 3.1.7 on 2021-08-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_customuser_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='session',
        ),
    ]
