# Generated by Django 3.1.7 on 2021-08-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_customuser_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.session'),
        ),
    ]
