# Generated by Django 3.1.7 on 2021-08-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210825_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='st_exam',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='st_first_test',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='st_second_test',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='st_third_test',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='tt_exam',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='tt_first_test',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='tt_second_test',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='tt_third_test',
        ),
    ]
