# Generated by Django 3.1.7 on 2021-08-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210825_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='st_exam',
            new_name='examination',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='st_first_test',
            new_name='first_ca',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='st_second_test',
            new_name='second_ca',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='st_third_test',
            new_name='third_ca',
        ),
    ]
