# Generated by Django 3.1.7 on 2021-08-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20210825_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='exams',
            new_name='tt_exam',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='first',
            new_name='tt_first_test',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='second',
            new_name='tt_second_test',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='third',
            new_name='tt_third_test',
        ),
    ]
