# Generated by Django 3.1.7 on 2021-08-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210825_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term')], max_length=50)),
            ],
        ),
    ]
