# Generated by Django 3.1.7 on 2021-08-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_selectterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectterm',
            name='term',
        ),
        migrations.AddField(
            model_name='selectterm',
            name='first_term',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='selectterm',
            name='second_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectterm',
            name='third_term',
            field=models.BooleanField(default=False),
        ),
    ]
