# Generated by Django 3.1.7 on 2021-08-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20210828_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychonmotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handwriting', models.IntegerField(default=1)),
                ('verbal_fluency', models.IntegerField(default=1)),
                ('games', models.IntegerField(default=1)),
                ('sports', models.IntegerField(default=1)),
                ('handing_tools', models.IntegerField(default=1)),
                ('drawing_and_painting', models.IntegerField(default=1)),
                ('musical_skills', models.IntegerField(default=1)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectTerm',
        ),
    ]
